# Generated by Django 6.0.5 on 2026-08-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_icon_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendor_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_area_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
